### ISSUE TITLE
[FIX] IssueControllerTest 실패 현상 수정

### ISSUE THREAD

**Issue by seedspirit** [codesquad-masters2024-team09/issue-tracker#2]
## 🔥 Fix Issue
IssueControllerTest의 create 테스트가 실패하는 현상 수정

### 상세 설명
- Redirect URL이 'issuses/1'로 나와야 하지만, 테스트의 결과는 'issues/0'으로 나와 fail하고 있음
- Postman으로 API 테스트하는 경우에는 'issues/1'로 정상 동작함

## ✅ TODO
 - [x] IssueControllerTest의 create 테스트 코드 수정
 - [x] Postman으로 한 번 더 테스트하기

**Comment by sharpie1330** [comment]
## 문제
```java
    @Test
    void create() throws Exception {
        // given
        final String url = "/issues";

        IssueCreateRequest request = new IssueCreateRequest("testMember", "testTitle", "testContent");
        final String requestJson = objectMapper.writeValueAsString(request);
        given(issueService.create(request)).willReturn(1L);

        // when
        final ResultActions result = mockMvc.perform(
                post(url).content(requestJson)
                        .contentType(MediaType.APPLICATION_JSON)
        );

        // then
        result.andExpect(status().isCreated())
                .andExpect(header().string("Location", "/issues/1"));
    }
```
given으로 서비스의 create() 메서드 호출 시 1L을 반환하도록 설정했다.
IssueController의 create() 메서드가 호출되면 서비스의 create() 메서드를 호출해 issueId를 반환하고, 컨토롤러는 해당 값을 받아 Location 헤더를 /issues/{issueId}로 설정해 응답한다. 따라서 result.andExpect()에서 Location 헤더가 `/issues/1`라는 값을 가지는지 확인했다.
그러나 mockMvc.perform()을 통해 설정된 헤더는 `/issues/0`였고, 따라서 테스트에 통과하지 못했다. 

## 발생 원인
해당 테스트 코드에서 직접 new로 생성한 IssueCreateRequest와 mockMvc.perform()에서 생성되는 IssueCreateRequest는 서로 다른 객체다. 내부 값은 같더라도 주소값이 다르다. 따라서 `given(issueService.create(request)).willReturn(1L);`이 호출되지 않았고, Mockito는 이 경우 기본값인 0을 반환한 것. 

## 해결 방법
`given(issueService.create(any(IssueCreateRequest.class))).willReturn(1L);`

Mockito의 any() 메서드를 사용해 해결했다. 위 구문은 어떤 IssueCreateRequest 타입이 매개변수로 전달되든 1L을 리턴하겠다는 것을 의미한다.
